/* ===== BUILDING DEFINITIONS — BIO GENESIS ===== */

const BUILDING_DEFS = {
    // === Extraction ===
    miner: {
        name: "Blood Harvester",
        category: "extraction",
        tier: 1,
        size: [2, 2],
        produces: { biomass: 1, algae: 1 },
        producesInterval: 3,
        inputs: [],
        energyCost: 1,
        color: "#5a1a1a",
        description: "Harvests biomass and blood algae from organic remains",
        unlockStage: 0,
    },
    coal_drill: {
        name: "Flesh Drill",
        category: "extraction",
        tier: 1,
        size: [2, 2],
        produces: { carbon: 2 },
        producesInterval: 2,
        inputs: [],
        energyCost: 1,
        color: "#6a2a2a",
        description: "Drills carbon from tissue",
        unlockStage: 0,
    },
    copper_miner: {
        name: "Tendon Extractor",
        category: "extraction",
        tier: 1,
        size: [2, 2],
        produces: { enzyme: 1 },
        producesInterval: 4,
        inputs: [],
        energyCost: 1,
        color: "#7a3030",
        description: "Extracts enzymes from tendons",
        unlockStage: 0,
    },

    // === Processing ===
    smelter: {
        name: "Blood Boiler",
        category: "processing",
        tier: 2,
        size: [2, 2],
        consumes: { biomass: 2, carbon: 1 },
        produces: { polymer: 1 },
        producesInterval: 5,
        inputs: ["biomass", "carbon"],
        energyCost: 2,
        color: "#8a2020",
        description: "Boils biomass into polymer",
        unlockStage: 1,
    },
    tissue_cultivator: {
        name: "Tissue Cultivator",
        category: "processing",
        tier: 2,
        size: [1, 1],
        produces: { polymer: 1 },
        producesInterval: 5,
        inputs: [],
        energyCost: 1,
        color: "#6a2040",
        description: "Grows polymer from living tissue — no input needed",
        unlockStage: 1,
    },
    gland_extractor: {
        name: "Gland Extractor",
        category: "processing",
        tier: 2,
        size: [1, 1],
        produces: { protein: 1 },
        producesInterval: 6,
        inputs: [],
        energyCost: 1,
        color: "#6a4020",
        description: "Extracts protein from glands — no input needed",
        unlockStage: 1,
    },
    furnace: {
        name: "Corpse Furnace",
        category: "processing",
        tier: 2,
        size: [2, 3],
        consumes: { biomass: 3, algae: 2 },
        produces: { biofuel: 2 },
        producesInterval: 4,
        inputs: ["biomass", "algae"],
        energyCost: 0,
        color: "#7a1a1a",
        description: "Burns remains into biofuel — generates +8 energy per cycle",
        generatesEnergy: true,
        energyGenerated: 8,
        unlockStage: 1,
    },
    copper_smelter: {
        name: "Muscle Refinery",
        category: "processing",
        tier: 2,
        size: [2, 2],
        consumes: { enzyme: 2, carbon: 1 },
        produces: { protein: 1 },
        producesInterval: 6,
        inputs: ["enzyme", "carbon"],
        energyCost: 2,
        color: "#9a3030",
        description: "Refines muscle tissue into protein",
        unlockStage: 1,
    },

    // === Manufacturing ===
    assembler: {
        name: "Corpse Stitcher",
        category: "manufacturing",
        tier: 3,
        size: [3, 2],
        consumes: { polymer: 2, protein: 1 },
        produces: { biocomponent: 1 },
        producesInterval: 8,
        inputs: ["polymer", "protein"],
        energyCost: 3,
        color: "#6a1a2a",
        description: "Stitches bio-components from polymer and protein",
        unlockStage: 2,
    },
    engine_factory: {
        name: "Heart Factory",
        category: "manufacturing",
        tier: 3,
        size: [3, 3],
        consumes: { biocomponent: 3, biofuel: 2, protein: 1 },
        produces: { bioorgan: 1 },
        producesInterval: 12,
        inputs: ["biocomponent", "biofuel", "protein"],
        energyCost: 3,
        color: "#5a1a1a",
        description: "Creates living organs from components and fuel",
        unlockStage: 3,
    },

    // === Support ===
    conveyor: {
        name: "Blood Conveyor",
        category: "extraction",
        tier: 1,
        size: [1, 1],
        produces: {},
        producesInterval: 0,
        inputs: [],
        isTransport: true,
        energyCost: 0,
        color: "#4a1a1a",
        description: "Transports resources through blood tubes",
        unlockStage: 0,
    },
    storage: {
        name: "Blood Sac",
        category: "extraction",
        tier: 1,
        size: [2, 2],
        produces: {},
        producesInterval: 0,
        inputs: [],
        isStorage: true,
        capacity: 100,
        energyCost: 0,
        color: "#5a2020",
        description: "Stores up to 100 units of resources",
        unlockStage: 0,
    },
    splitter: {
        name: "Blood Splitter",
        category: "extraction",
        tier: 1,
        size: [1, 1],
        produces: {},
        producesInterval: 0,
        inputs: [],
        isTransport: true,
        energyCost: 0,
        color: "#6a2a2a",
        description: "Splits resource flow into two directions",
        unlockStage: 0,
    },
    smart_conveyor: {
        name: "Smart Conveyor",
        category: "extraction",
        tier: 1,
        size: [1, 1],
        produces: {},
        producesInterval: 0,
        inputs: [],
        isTransport: true,
        isSmartConveyor: true,
        energyCost: 0,
        color: "#3a3a1a",
        description: "Smart conveyor — select which resources to transport",
        unlockStage: 3,
    },
};

/* ===== EMBRYOLOGICAL DEVELOPMENT STAGES ===== */

const STAGES = [
    {
        name: "First Cell",
        nameEn: "Fertilization",
        cycleThreshold: 0,
        timeThreshold: 0,
        color: "#4a1a2a",
        desc: "Egg and sperm unite into a single cell — the spark of life",
        requirements: "Extract Biomass and Blood Algae with Blood Harvester",
        requiredProduction: {},
        cinematic: [
            { text: "In the realm beyond the clouds, where light and shadow weave the fabric of existence...", duration: 5000 },
            { text: "A spark ignites — a single cell, the first breath of life, pulsing with the energy of a thousand stars.", duration: 5000 },
            { text: "You are the Chosen Creator — a worker in Heaven, tasked with the sacred duty of building a human being from nothing.", duration: 5000 },
            { text: "Every soul begins as a single point — a convergence of matter and will, destined to become something greater.", duration: 5000 },
            { text: "From the dust of ancient stars, the first cell forms — fragile, yet infinite in its potential.", duration: 5000 },
            { text: "Begin your work. Harvest the essence of life. The journey of creation has begun.", duration: 5000 },
            { text: "For in every drop of blood, there is a universe waiting to be born.", duration: 5000 },
        ],
    },
    {
        name: "Embryo",
        nameEn: "Embryo",
        cycleThreshold: 20,
        timeThreshold: 25,
        color: "#5a1a2a",
        desc: "Cells divide to form the first tissue layers",
        requirements: "Produce 20 Biomass, 10 Algae, 15 Carbon",
        requiredProduction: { biomass: 20, algae: 10, carbon: 15 },
        cinematic: [
            { text: "The first cell divides — one becomes two, two becomes many, as life follows its ancient blueprint.", duration: 5000 },
            { text: "In the silence of creation, a new form emerges — the embryo, the template of all that will be.", duration: 5000 },
            { text: "Each division is a prayer. Each cell carries the memory of what it will become.", duration: 5000 },
            { text: "The heavens watch as the sacred pattern unfolds — layer upon layer, the body takes its first shape.", duration: 5000 },
            { text: "You are the hands that guide this growth. Feed it with biomass, the flesh of creation.", duration: 5000 },
            { text: "From carbon comes structure. From algae comes vitality. These are the gifts of the first life.", duration: 5000 },
            { text: "Creation demands sacrifice — give what is needed, and the embryo will grow into something magnificent.", duration: 5000 },
        ],
    },
    {
        name: "Neural Tube",
        nameEn: "Neural Tube",
        cycleThreshold: 45,
        timeThreshold: 70,
        color: "#5a2a1a",
        desc: "Neural tube forms — the brain and spine begin to take shape",
        requirements: "Collect 15 Polymer and 10 Protein in Blood Sac",
        requiredProduction: { polymer: 15, protein: 10 },
        cinematic: [
            { text: "A tube of light forms along the back of the embryo — the neural tube, the seed of consciousness.", duration: 5000 },
            { text: "Within this slender channel, billions of neurons await their calling — to think, to feel, to dream.", duration: 5000 },
            { text: "The spine extends like a river of silver, connecting mind to body, thought to action, soul to flesh.", duration: 5000 },
            { text: "You hold the tools of synthesis now — polymer and protein, the building blocks of nerve and mind.", duration: 5000 },
            { text: "Every thought this being will ever have begins here, in this quiet moment of formation.", duration: 5000 },
            { text: "What will they dream of, when the mind awakens? What prayers will rise from this neural fire?", duration: 5000 },
            { text: "Feed the neural tube. Shape the mind. The consciousness of a new life is being woven by your hands.", duration: 5000 },
        ],
    },
    {
        name: "Heartbeat",
        nameEn: "Cardiovascular",
        cycleThreshold: 90,
        timeThreshold: 160,
        color: "#6a1a1a",
        desc: "The heart begins to beat — circulation starts for the first time",
        requirements: "Collect 15 Biofuel and 10 Bio Components in Blood Sac",
        requiredProduction: { biofuel: 15, biocomponent: 10 },
        cinematic: [
            { text: "A rhythm emerges from the silence — thump-thump, thump-thump — the first heartbeat of a new being.", duration: 5000 },
            { text: "Blood begins to flow through tiny vessels, carrying life to every corner of the growing form.", duration: 5000 },
            { text: "The heart knows no master — it beats by its own will, a drum of existence that will not stop until the end.", duration: 5000 },
            { text: "You hear it now — the pulse of creation, resonating through the fabric of your sacred work.", duration: 5000 },
            { text: "Biofuel courses through the veins like liquid fire, powering the engine of life itself.", duration: 5000 },
            { text: "Bio-components assemble into vessels and valves, each one a tiny miracle of biological engineering.", duration: 5000 },
            { text: "The circulation strengthens. The heart grows bold. Soon, the organs will follow its rhythm.", duration: 5000 },
        ],
    },
    {
        name: "Organogenesis",
        nameEn: "Organogenesis",
        cycleThreshold: 180,
        timeThreshold: 320,
        color: "#7a1a2a",
        desc: "All organs grow and mature — the body becomes whole",
        requirements: "Collect 5 Bio Organs in Blood Sac",
        requiredProduction: { bioorgan: 5 },
        cinematic: [
            { text: "The organs awaken one by one — lungs draw their first phantom breath, kidneys filter the waters of life.", duration: 5000 },
            { text: "Liver and spleen, stomach and intestines — each organ a cathedral of cells, performing its sacred function.", duration: 5000 },
            { text: "The eyes form in darkness, waiting for the light they will one day see — the first window to the world.", duration: 5000 },
            { text: "You have come so far, Creator. From a single cell to a symphony of organs, each one singing its own note of life.", duration: 5000 },
            { text: "Bio-organs mature and intertwine, a network of living systems working in perfect harmony.", duration: 5000 },
            { text: "The body is nearly complete. Soon, it will be ready to leave the sanctuary of creation.", duration: 5000 },
            { text: "Ten more organs. Ten more miracles. Then the final stage awaits — birth.", duration: 5000 },
        ],
    },
    {
        name: "Birth",
        nameEn: "Birth",
        cycleThreshold: 300,
        timeThreshold: 500,
        color: "#8a2a2a",
        desc: "New life is ready to open its eyes — creation complete!",
        requirements: "Life is complete — all requirements met!",
        requiredProduction: {},
        cinematic: [
            { text: "The moment arrives — the final threshold between creation and existence.", duration: 5000 },
            { text: "Nine months of celestial work compressed into cycles of blood and bone, polymer and protein.", duration: 5000 },
            { text: "The lungs expand. The heart races. The eyes flutter open to a world of light and sound.", duration: 5000 },
            { text: "You have built a human being — from a single cell to a complete soul, breathing and alive.", duration: 5000 },
            { text: "Every machine you placed, every connection you made, every drop of energy you channeled led to this moment.", duration: 5000 },
            { text: "The baby cries — not in pain, but in recognition. It knows it exists. It knows you were here.", duration: 5000 },
            { text: "In the realm beyond the clouds, the workers of Heaven pause to witness what you have created.", duration: 5000 },
            { text: "From cell to embryo... from neural tube to heartbeat... from organs to birth — the cycle of life is complete.", duration: 5000 },
            { text: "You are no longer just a worker in Heaven. You are a Creator. And this life is your testament.", duration: 5000 },
            { text: "The factory falls silent. Its purpose fulfilled. Blood and bone, sinew and soul — all woven into one.", duration: 5000 },
            { text: "The baby opens its eyes and sees you. In that gaze, an entire universe of meaning unfolds.", duration: 5000 },
            { text: "You have given life. There is no greater act in all of creation. Rest now, Creator. Your work is done.", duration: 5000 },
            { text: "And somewhere, in a world beyond worlds, a new soul begins its journey — because you chose to create.", duration: 5000 },
            { text: "From Cell to Soul. The Blood Factory has fulfilled its purpose. Life continues. The story never ends.", duration: 5000 },
            { text: "Thank you, Creator. The universe remembers what you built here today.", duration: 5000 },
            { text: "— Blood Factory: From Cell to Soul — A story written in blood, bone, and the will to create. —", duration: 5000 },
            { text: "— The End —", duration: 5000 },
            { text: "— Or perhaps... the beginning. —", duration: 5000 },
        ],
    },
];

const RESOURCE_TYPES = {
    biomass:      { name: "Biomass",      color: "#8a3030" },
    algae:        { name: "Blood Algae",   color: "#6a2020" },
    carbon:       { name: "Carbon",        color: "#4a4a3a" },
    enzyme:       { name: "Enzyme",        color: "#9a6030" },
    polymer:      { name: "Polymer",       color: "#8a4040" },
    biofuel:      { name: "Biofuel",       color: "#aa3030" },
    protein:      { name: "Protein",       color: "#8a6a40" },
    biocomponent: { name: "Bio Component", color: "#7a3a3a" },
    bioorgan:     { name: "Bio Organ",     color: "#9a2a2a" },
};

const CATEGORY_INFO = {
    extraction:    { name: "Extraction",    icon: "⛏" },
    processing:    { name: "Processing",    icon: "🧬" },
    manufacturing: { name: "Manufacturing", icon: "🔬" },
};
